name:                DataVersion
version:             0.1.0.0
github:              "agentultra/DataMigration"
license:             MIT
author:              "Sandy Maguire, James King"
maintainer:          "james@agentultra.com"
copyright:           "2019 Sandy Maguire, James King"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Type safe data migrations
category: Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/agentultra/DataMigration#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - microlens >=0.4.10 && <2
    - generic-lens >=1.1.0.0 && <2

default-extensions:
  - DataKinds
  - TypeFamilies
  - QuantifiedConstraints
  - DeriveGeneric
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - PolyKinds
  - AllowAmbiguousTypes
  - DuplicateRecordFields
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - UndecidableInstances

tests:
  DataMigration-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DataMigration
    - hspec
    - QuickCheck
